version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "bundler"
    open-pull-requests-limit: 99
      
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "gh"
    open-pull-requests-limit: 99
